/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orangesunshine_ndk_LameActivity */

#ifndef _Included_com_orangesunshine_ndk_LameActivity
#define _Included_com_orangesunshine_ndk_LameActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orangesunshine_ndk_LameActivity
 * Method:    convertMp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_orangesunshine_ndk_LameActivity_convertMp3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_orangesunshine_ndk_LameActivity
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_orangesunshine_ndk_LameActivity_getLameVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
